//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B2BAISERA.Models.EFServer
{
    public partial class CUSTOMGR
    {
        #region Primitive Properties
    
        public virtual string PONUMBER
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ACTUALRECEIVEDUNIT
        {
            get;
            set;
        }
    
        public virtual string NOCHASIS
        {
            get;
            set;
        }
    
        public virtual string NOENGINE
        {
            get;
            set;
        }
    
        public virtual string NOEQUIP
        {
            get;
            set;
        }
    
        public virtual string NOEQUIPBARU
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLCREATEEQUIP
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLGRSAP
        {
            get;
            set;
        }
    
        public virtual string NAMAPEMILIK
        {
            get;
            set;
        }
    
        public virtual string VENDORNAMEAP
        {
            get;
            set;
        }
    
        public virtual string PICRECEIVEDUNIT
        {
            get;
            set;
        }
    
        public virtual string STATUSDELIVERYUNIT
        {
            get;
            set;
        }
    
        public virtual string MODIFIED_BY
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> MODIFIED_DATE
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ACTUALRECEIVEDUNITINBDEL
        {
            get;
            set;
        }
    
        public virtual string NOCHASIS_INPUT
        {
            get;
            set;
        }
    
        public virtual string NOENGINE_INPUT
        {
            get;
            set;
        }
    
        public virtual string NAMAPEMILIK_INPUT
        {
            get;
            set;
        }

        #endregion
    }
}
