//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace B2BAISERA.Models.EFServer
{
    public partial class EProcEntities : ObjectContext
    {
        public const string ConnectionString = "name=EProcEntities";
        public const string ContainerName = "EProcEntities";
    
        #region Constructors
    
        public EProcEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public EProcEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public EProcEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<CUSTOM_DOWNLOAD_TRANSACTION> CUSTOM_DOWNLOAD_TRANSACTION
        {
            get { return _cUSTOM_DOWNLOAD_TRANSACTION  ?? (_cUSTOM_DOWNLOAD_TRANSACTION = CreateObjectSet<CUSTOM_DOWNLOAD_TRANSACTION>("CUSTOM_DOWNLOAD_TRANSACTION")); }
        }
        private ObjectSet<CUSTOM_DOWNLOAD_TRANSACTION> _cUSTOM_DOWNLOAD_TRANSACTION;
    
        public ObjectSet<CUSTOM_DOWNLOAD_TRANSACTIONDATA> CUSTOM_DOWNLOAD_TRANSACTIONDATA
        {
            get { return _cUSTOM_DOWNLOAD_TRANSACTIONDATA  ?? (_cUSTOM_DOWNLOAD_TRANSACTIONDATA = CreateObjectSet<CUSTOM_DOWNLOAD_TRANSACTIONDATA>("CUSTOM_DOWNLOAD_TRANSACTIONDATA")); }
        }
        private ObjectSet<CUSTOM_DOWNLOAD_TRANSACTIONDATA> _cUSTOM_DOWNLOAD_TRANSACTIONDATA;
    
        public ObjectSet<CUSTOM_DOWNLOAD_TRANSACTIONDATADETAIL> CUSTOM_DOWNLOAD_TRANSACTIONDATADETAIL
        {
            get { return _cUSTOM_DOWNLOAD_TRANSACTIONDATADETAIL  ?? (_cUSTOM_DOWNLOAD_TRANSACTIONDATADETAIL = CreateObjectSet<CUSTOM_DOWNLOAD_TRANSACTIONDATADETAIL>("CUSTOM_DOWNLOAD_TRANSACTIONDATADETAIL")); }
        }
        private ObjectSet<CUSTOM_DOWNLOAD_TRANSACTIONDATADETAIL> _cUSTOM_DOWNLOAD_TRANSACTIONDATADETAIL;
    
        public ObjectSet<CUSTOM_S02008> CUSTOM_S02008
        {
            get { return _cUSTOM_S02008  ?? (_cUSTOM_S02008 = CreateObjectSet<CUSTOM_S02008>("CUSTOM_S02008")); }
        }
        private ObjectSet<CUSTOM_S02008> _cUSTOM_S02008;
    
        public ObjectSet<CUSTOM_LOG> CUSTOM_LOG
        {
            get { return _cUSTOM_LOG  ?? (_cUSTOM_LOG = CreateObjectSet<CUSTOM_LOG>("CUSTOM_LOG")); }
        }
        private ObjectSet<CUSTOM_LOG> _cUSTOM_LOG;
    
        public ObjectSet<CUSTOM_USER> CUSTOM_USER
        {
            get { return _cUSTOM_USER  ?? (_cUSTOM_USER = CreateObjectSet<CUSTOM_USER>("CUSTOM_USER")); }
        }
        private ObjectSet<CUSTOM_USER> _cUSTOM_USER;
    
        public ObjectSet<CUSTOMGR> CUSTOMGRs
        {
            get { return _cUSTOMGRs  ?? (_cUSTOMGRs = CreateObjectSet<CUSTOMGR>("CUSTOMGRs")); }
        }
        private ObjectSet<CUSTOMGR> _cUSTOMGRs;
    
        public ObjectSet<CUSTOMPO> CUSTOMPOes
        {
            get { return _cUSTOMPOes  ?? (_cUSTOMPOes = CreateObjectSet<CUSTOMPO>("CUSTOMPOes")); }
        }
        private ObjectSet<CUSTOMPO> _cUSTOMPOes;

        #endregion
        #region Function Imports
        public ObjectResult<Nullable<int>> sp_UpdateS02008(string pONUMBER, Nullable<int> vERSIONPOSERA, Nullable<int> dATAVERSION, string sALESORDERNO, string nOCHASIS_INPUT, Nullable<System.DateTime> tGLMASUKKAROSERI)
        {
    
            ObjectParameter pONUMBERParameter;
    
            if (pONUMBER != null)
            {
                pONUMBERParameter = new ObjectParameter("PONUMBER", pONUMBER);
            }
            else
            {
                pONUMBERParameter = new ObjectParameter("PONUMBER", typeof(string));
            }
    
            ObjectParameter vERSIONPOSERAParameter;
    
            if (vERSIONPOSERA.HasValue)
            {
                vERSIONPOSERAParameter = new ObjectParameter("VERSIONPOSERA", vERSIONPOSERA);
            }
            else
            {
                vERSIONPOSERAParameter = new ObjectParameter("VERSIONPOSERA", typeof(int));
            }
    
            ObjectParameter dATAVERSIONParameter;
    
            if (dATAVERSION.HasValue)
            {
                dATAVERSIONParameter = new ObjectParameter("DATAVERSION", dATAVERSION);
            }
            else
            {
                dATAVERSIONParameter = new ObjectParameter("DATAVERSION", typeof(int));
            }
    
            ObjectParameter sALESORDERNOParameter;
    
            if (sALESORDERNO != null)
            {
                sALESORDERNOParameter = new ObjectParameter("SALESORDERNO", sALESORDERNO);
            }
            else
            {
                sALESORDERNOParameter = new ObjectParameter("SALESORDERNO", typeof(string));
            }
    
            ObjectParameter nOCHASIS_INPUTParameter;
    
            if (nOCHASIS_INPUT != null)
            {
                nOCHASIS_INPUTParameter = new ObjectParameter("NOCHASIS_INPUT", nOCHASIS_INPUT);
            }
            else
            {
                nOCHASIS_INPUTParameter = new ObjectParameter("NOCHASIS_INPUT", typeof(string));
            }
    
            ObjectParameter tGLMASUKKAROSERIParameter;
    
            if (tGLMASUKKAROSERI.HasValue)
            {
                tGLMASUKKAROSERIParameter = new ObjectParameter("TGLMASUKKAROSERI", tGLMASUKKAROSERI);
            }
            else
            {
                tGLMASUKKAROSERIParameter = new ObjectParameter("TGLMASUKKAROSERI", typeof(System.DateTime));
            }
            return base.ExecuteFunction<Nullable<int>>("sp_UpdateS02008", pONUMBERParameter, vERSIONPOSERAParameter, dATAVERSIONParameter, sALESORDERNOParameter, nOCHASIS_INPUTParameter, tGLMASUKKAROSERIParameter);
        }

        #endregion
    }
}
